apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  os: { name: linux }
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - name: test
      image: ubuntu
      imagePullPolicy: IfNotPresent
      command:
        - "/bin/bash"
        - "-c"
        - "--"
      args:
        - "sleep 86400 & wait"
      volumeMounts:
        - name: host
          mountPath: /mnt/host
          readOnly: true
        - name: storage
          mountPath: /storage
  restartPolicy: Never
  volumes:
    - name: host
      hostPath:
        path: /
        type: Directory
    - name: storage
      persistentVolumeClaim:
        claimName: gpu-driver

---

apiVersion: v1
kind: Pod
metadata:
  name: test2
spec:
  os: { name: linux }
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - name: test2
      image: ubuntu
      imagePullPolicy: IfNotPresent
      command:
        - "/bin/bash"
        - "-c"
        - "--"
      args:
        - "sleep 86400 & wait"
      volumeMounts:
        - name: host
          mountPath: /mnt/host
          readOnly: true
        - name: storage
          mountPath: /storage
          readOnly: true
  restartPolicy: Never
  volumes:
    - name: host
      hostPath:
        path: /
        type: Directory
    - name: storage
      persistentVolumeClaim:
        claimName: gpu-driver
