apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gpu-driver-installer
    app.kubernetes.io/part-of: gpu-driver
  name: installer
  namespace: system
