# This rule is not used by the project gpu-driver itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over gpu.kyma-project.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gpu-driver
    app.kubernetes.io/managed-by: kustomize
  name: gpudriver-admin-role
rules:
- apiGroups:
  - gpu.kyma-project.io
  resources:
  - gpudrivers
  verbs:
  - '*'
- apiGroups:
  - gpu.kyma-project.io
  resources:
  - gpudrivers/status
  verbs:
  - get
