# This rule is not used by the project gpu-driver itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to gpu.kyma-project.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gpu-driver
    app.kubernetes.io/managed-by: kustomize
  name: gpudriver-viewer-role
rules:
- apiGroups:
  - gpu.kyma-project.io
  resources:
  - gpudrivers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gpu.kyma-project.io
  resources:
  - gpudrivers/status
  verbs:
  - get
