apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ template "chart.fullname" . }}-installer
  name: {{ template "chart.fullname" . }}-installer

---

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "chart.fullname" . }}-installer
  labels:
    app.kubernetes.io/name: {{ template "chart.fullname" . }}-installer
    app.kubernetes.io/part-of: {{ template "chart.fullname" . }}
rules:
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: [""]
    resources:
      - nodes/status
      - pods/status
    verbs:
      - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ template "chart.fullname" . }}-installer
    app.kubernetes.io/part-of: {{ template "chart.fullname" . }}
  name: {{ template "chart.fullname" . }}-installer
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "chart.fullname" . }}-installer
subjects:
  - kind: ServiceAccount
    name: {{ template "chart.fullname" . }}-installer
    namespace: {{ .Release.Namespace }}
