
# Not created by the installation, but by the maintainer/SRE.
# Some of the values are defaulted in the operator source code
# and those provided here are the overrides/addons to those hard-coded defaults
# As new Garden Linux versions get released, this CR is created/updated with the
# additional mappings resulting in no need to reinstall/upgrade the operator
apiVersion: gpu.kyma-project.io
kind: VersionMapping
spec:
  kmodbuildVersions: # used to pick appropriate kmodbuild version with matching kernel
    "6.6.62-cloud-amd64": "amd64-1592.3"
    "6.6.63-cloud-amd64": "amd64-1592.4"
    "6.6.71-cloud-amd64": "amd64-1592.5"
    "6.6.78-cloud-amd64": "amd64-1592.6"
  driverVersions: # used to pick driver version if not specified by the user
    "6.6.62-cloud-amd64": "550.127.08"
    "6.6.63-cloud-amd64": "555.42.06"
    "6.6.71-cloud-amd64": "560.35.05"
---

# Created by the user to specify a set of nodes where to install the driver
# User can create more than one of these CRs with different settings for different sets of nodes.
# Operator adds a finalizer to ensure all resources created by the operator are removed before
# this resource is deleted.
apiVersion: gpu.kyma-project.io
kind: GpuDriver
spec:
  nodeSelector: # required
    some-label: value
  driverVersion: "550.127.08"
  installer:
    imagePullSecrets: []
    repository: ghcr.io
    image: gardenlinux/gardenlinux/kmodbuild
  fabricManager:
    enabled: true
    imagePullSecrets: []
    repository: ""
    image: bitnami/minideb
    version: bookworm
  devicePlugin:
    enabled: true
    imagePullSecrets: []
    repository: gcr.io
    image: gke-release/nvidia-gpu-device-plugin
    version: 1.0.25-gke.56

