apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gpu-driver.name" . }}
  namespace: {{ .Release.Namespace }}
data:
{{- range $path, $_ := .Files.Glob "files/gardenlinux-nvidia-installer/*.sh" }}
  {{ base $path }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
{{- range $path, $_ := .Files.Glob "files/*.sh" }}
  {{ base $path }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
