{{- range $kernel, $tag := .Values.kernelVersions }}
{{- $safeKernel := ($kernel | replace "." "-") -}}
{{- $valuesOverlay := dict "kernel" $kernel "safeKernel" $safeKernel -}}
{{- $rootOverlay := dict "Values" $valuesOverlay -}}
{{- $root := merge $rootOverlay $ }}
---
#
# kernel: {{ $kernel }}
# safeKernel {{ $safeKernel }}
#
#
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "gpu-driver.name" $root }}-{{ $root.Values.safeKernel }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    gpu.kyma-project.io/kernel-version: "{{ $root.Values.kernel }}"
    gpu.kyma-project.io/build-image-version: "{{ $tag }}"
spec:
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      name: {{ template "gpu-driver.name" $root }}
  template:
    metadata:
      labels:
        name: {{ template "gpu-driver.name" $root }}
        gpu.kyma-project.io/kernel-version: "{{ $root.Values.kernel }}"
        gpu.kyma-project.io/build-image-version: "{{ $tag }}"
    spec:
      priorityClassName: system-node-critical
      {{- if $root.Values.nodeAffinity }}
      affinity:
        nodeAffinity:
{{ toYaml $root.Values.nodeAffinity | indent 10 }}
      {{- end }}
      hostPID: true
      imagePullSecrets: {{ template "image-pull-secrets" $ }}
      containers:
      - name: gpu-driver
        {{- $imageUri := $root.Values.gardenlinux.image }}
        {{- if $root.Values.gardenlinux.imageRegistry }}
          {{ $imageUri = printf "%s/%s" $root.Values.gardenlinux.imageRegistry $imageUri }}
        {{- end }}
        image: {{ $imageUri }}:{{ $tag }}
        workingDir: "/work"
        command:
          - "/work/entrypoint.sh"
        securityContext:
          privileged: true
{{- if $root.Values.nvidia.installer.resources }}
        resources:
{{ toYaml $root.Values.nvidia.installer.resources | indent 12 }}
{{- end }}
        env:
          - name: KERNEL_TYPE
            value: cloud
          - name: TARGET_ARCH
            value: amd64
          - name: DRIVER_VERSION
            value: 550.127.08
          - name: LD_ROOT
            value: /root
          - name: DEBUG
            value: {{ $root.Values.debug | quote }}
          - name: HOST_DRIVER_PATH
            value: {{ $root.Values.nvidia.installer.hostDriverPath }}
        volumeMounts:
          - name: gpu-driver
            mountPath: /work
          - name: dev
            mountPath: /dev
          - name: ld-root
            mountPath: /root
          - name: module-cache
            mountPath: /opt/nvidia-installer/cache
          - name: module-install-dir-base
            mountPath: {{ required "nvidia.installer.hostDriverPath" $root.Values.nvidia.installer.hostDriverPath }}
      {{ template "node-selector.with-kernel" $root }}
{{- if $root.Values.tolerations }}
      tolerations:
{{ toYaml $root.Values.tolerations | indent 6 }}
{{- end }}
      volumes:
        - name: gpu-driver
          configMap:
            name: {{ template "gpu-driver.name" $ }}
            defaultMode: 0744
        - name: dev
          hostPath:
            path: /dev
        - name: ld-root
          hostPath:
            path: /
        - name: module-cache
          hostPath:
            path: /opt/nvidia-installer/cache
        - name: module-install-dir-base
          hostPath:
            path: {{ required "nvidia.installer.hostDriverPath" $root.Values.nvidia.installer.hostDriverPath }}

{{- end }}
