apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "rbac.name" . }}
  namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "rbac.name" . }}
rules:
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - update
      - patch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "rbac.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "rbac.name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "rbac.name" . }}
  apiGroup: rbac.authorization.k8s.io
