---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gpu-driver-installer
  labels:
    app.kubernetes.io/name: gpu-driver-installer
    app.kubernetes.io/part-of: gpu-driver-operator
rules:
- apiGroups:
  - v1
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - v1
  resources:
  - nodes/status
  - pods/status
  verbs:
  - get
