apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: test
      image: ghcr.io/tmilos77/gpu-test:cuda
      imagePullPolicy: Always
      resources:
        limits:
          nvidia.com/gpu: '1'
  restartPolicy: Never
