name: Cloud-Manager Build Image

on:
  push:
    tags:
      - "container-*"

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  version:
    if: startsWith(github.ref_name, 'container-')
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - id: version
        run: |
          TAG=${{ github.ref_name }}
          echo "version=${TAG#container-}" >> "$GITHUB_OUTPUT"

  build-image:
    if: startsWith(github.ref_name, 'container-')
    strategy:
      matrix:
        arch: ["amd64"]
        driver_version: ["550.127.08"]
    needs: [version]
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      tags: |
        ${{ needs.version.outputs.version }}-${{ matrix.driver_version }}-${{ matrix.arch }}
      name: gpu-driver
      dockerfile: Dockerfile
      export-tags: true
      build-args: |
        TARGET_ARCH=${{ matrix.arch }}
        DRIVER_VERSION=${{ matrix.driver_version }}
