name: GPU Driver Build Image

on:
  push:
    branches:
      - main
    tags:
      - "[0-9]*"

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: write # This is required for actions/checkout

jobs:
  build-image:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      tags: ${{ github.ref_name }}
      name: gpu-driver
      dockerfile: Dockerfile
      export-tags: true

  create-release:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate dist files
        run: |
          make dist-all

      - name: Check for modified files
        run: git diff --exit-code

      - name: Prepare release files
        run: |
          cp config/dist/all.yaml crds.yaml
          cp config/dist/default-cr.yaml gpudriver-default-cr.yaml

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Release Notes
          files: |
            crds.yaml
            gpudriver-default-cr.yaml
