name: Cloud-Manager Build Image

on:
  push:
    branches:
      - main
    tags:
      - "*"

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  build-image:
    strategy:
      matrix:
        arch: ["amd64"]
        driver_version: ["550.127.08"]
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      tags: "${{ matrix.driver_version }}-${{ matrix.arch }}"
      name: gpu-driver
      dockerfile: Dockerfile
      export-tags: true
      build-args:
        TARGET_ARCH: ${{ matrix.arch }}
        DRIVER_VERSION: ${{ matrix.driver_version }}
