name: GPU Driver Build Image

on:
  push:
    branches:
      - main
    tags:
      - "[0-9]*"

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  build-image:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      tags: ${{ github.ref_name }}
      name: gpu-driver
      dockerfile: Dockerfile
      export-tags: true
