name: GPU Driver Build Image PR

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  guard-image-build:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'pr-build-image') }}
    runs-on: ubuntu-latest
    environment: guard-image-build
    steps:
      - run: echo "Build approved"

  build-image:
    needs: guard-image-build
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: gpu-driver
      dockerfile: Dockerfile
      export-tags: true
