on:
  workflow_call:
    inputs:
      release:
        type: string
        required: true

name: GPU Driver Module Release

jobs:
  update-release:
    uses: actions/upload-release-asset@v1
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      release_id: ${{ inputs.release }}
      asset_path: config/dist/all.yaml
      asset_name: crds.yaml
      asset_content_type: application/json